name: Install BICEP Template

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: '!/.github/*'
    
jobs:
  deployBicep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Azure Resource Manager (ARM) BICEP Template
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: 2c64efa2-a67e-434f-b039-8a2fe69589bf
          resourceGroupName: TestGitHubAction-rg
          template: main.bicep
      
      - name: Azure logout
        run: |
          az logout
